# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    environment: 
      IMAGE_NAME: scottlifts/lorem-ipsum-app
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
        name: Build Docker Image
        command: docker build -t $IMAGE_NAME:latest
  publish-latest:
    environment: 
      IMAGE_NAME: lorem-ipsum-app
    docker:
      - image: ubuntu:latest
    steps:
      - run:
        name: Publish image to Docker Hub
        command: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $IMAGE_NAME:latest
workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master
      - publish-latest:
        requires:
          - build
        filters:
          branches:
            only: master
